#!/bin/bash

set -eu

function main()
{
    download_list

    local categories=${1:-$(find blacklists -type d)}

    for category in $categories
    do
        test_file "$category" 'domains' &
        test_file "$category" 'urls' &
    done

    wait
}

function download_list()
{
    if [ ! -e 'blacklists' ]
    then
        wget ftp://ftp.ut-capitole.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz -O - | tar xz
    fi
}

function test_file()
{
    local category=$1
    local file="$category/$2"

    if [ ! -e "$file" ]
    then
        return
    fi

    for url in $(cat "$file")
    do
        test_url "$(basename $category)" "http://$url/"
    done
}

function test_url()
{
    local category=$1
    local domain=$2
    local status=$(status_code "$url")
    local blocked='false'
    local location=''

    if [[ "$status" == "302" ]]
    then
        location=$(location "$url")

        if [[ $location == https://controller.access.network/403.html* ]]
        then
            blocked='true'
        fi
    fi

    echo "$category	$url	$status	$blocked"
}

function status_code()
{
    local url=$1

    curl --connect-timeout 2 --write-out "%{http_code}" --silent --output /dev/null -- "$url"
}

function location()
{
    local url=$1

    curl --location --connect-timeout 2 --write-out "%{url_effective}" --silent --output /dev/null -- "$url"
}

main $@
